remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
highlighter: pygments
# posts per page where you use pagination
paginate: 2
baseurl: /
#exclude:
#- README.md
title: "Svitlana Orlova's personal page"
description: "Links, projects, documents"
